version: "3.8"

services:
  python_api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - neo4j
  neo4j:
    image: neo4j:latest
    container_name: neo4j_local
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/password
    volumes:
      - ./data:/var/lib/neo4j/data
